# Generated by Django 4.2 on 2023-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="airfoil_exp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f", models.FloatField()),
                ("alpha", models.FloatField()),
                ("c", models.FloatField()),
                ("U_infinity", models.FloatField()),
                ("delta", models.FloatField()),
                ("SSPL", models.FloatField()),
            ],
        ),
    ]
