base:
  project: mlops-airfoil
  random_state: 20
  target_col: SSPL

data_source:
  s3_source: source_code/airfoil_nasa.csv
  
load_data:
  raw_dataset_csv: data/raw/airfoil_nasa.csv

split_data:
  train_path: data/processed/train_airfoil_nasa.csv
  test_path: data/processed/test_airfoil_nasa.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4

model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib